name: Build WSL2 Kernel Manually

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Branch or tag to build'
        required: true
        default: 'linux-msft-wsl-5.10.16.3'

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout from Official Microsoft Repo
        uses: actions/checkout@v4
        with:
          # 直接指定从微软的官方仓库 checkout，而不是从你的fork仓库
          repository: 'microsoft/WSL2-Linux-Kernel'
          # 使用你输入的 tag (例如 'linux-msft-wsl-5.4.72')
          ref: ${{ github.event.inputs.tag }}
          # 只下载最新的 commit，节省时间
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential flex bison libssl-dev libelf-dev libncurses-dev dwarves

      - name: Build Kernel
        run: |
          cp /proc/config.gz .
          gunzip config.gz
          make -j$(nproc) bzImage

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wsl2-kernel
          path: arch/x86/boot/bzImage
