name: Build WSL2 Kernel Manually

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Branch or tag to build'
        required: true
        default: 'linux-msft-4.19.128'

jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout from Official Microsoft Repo with Full History
        uses: actions/checkout@v4
        with:
          repository: 'microsoft/WSL2-Linux-Kernel'
          ref: ${{ github.event.inputs.tag }}
          fetch-depth: 0

      - name: Install Dependencies and older GCC
        run: |
          sudo apt-get update
          # 安装编译依赖以及与旧内核更兼容的 gcc-9
          sudo apt-get install -y git build-essential flex bison libssl-dev libelf-dev libncurses-dev dwarves gcc-9 g++-9

      - name: Build Kernel
        run: |
          # 使用 export 命令，确保 objtool= 的设置能被所有子 make 进程继承
          export objtool=
          # 明确指定使用 gcc-9 作为编译器
          make -j$(nproc) CC=gcc-9 bzImage
